import { type NextPage } from "next";
// import Head from "next/head";
// import Link from "next/link";
import { useSession } from "next-auth/react";
import dynamic from "next/dynamic";
import { useEffect } from "react";
import LoginForm from "../components/Loginform";
import { useAppDispatch } from "../hooks/useTypedSelector";
import { setActiveList } from "../slices/listSlice";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const HomepageLayoutComponent = dynamic(
    async () => await import("./../components/layouts/homepage/HomePageLayout"),
    {
      ssr: false,
    }
  );
  // console.log("session: ", session);
  // console.log("status: ", status);
  //const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  console.log("INDEX>TSX FIRING");

  // reset of ActiveList on returning to homepage/checking session. Might need to move this up one level in the future!
  const dispatch = useAppDispatch();
  useEffect(() => {
    dispatch(setActiveList(undefined));
  }, []);
  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className="h-screen">
        {session ? (
          <HomepageLayoutComponent />
        ) : (
          <div className="">
            <LoginForm />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
